apiVersion: apps/v1
kind: Deployment
metadata:
  name: arithmetic-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arithmetic-service
  template:
    metadata:
      labels:
        app: arithmetic-service
    spec:
      containers:
        - name: arithmetic-service
          image: arithmetic-service:1
          ports:
            - containerPort: 8080
apiVersion: v1
kind: Service
metadata:
  name: arithmetic-service
spec:
  type: NodePort
  selector:
    app: arithmetic-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
